### ISSUE TITLE
docker部署控制台报错  登陆进去没有任何反应

### ISSUE THREAD

**Issue by yangzhenwei-java** [shibingli/webconsole#45]
console.min.js:1 WebSocket connection to 'ws://10.0.8.122:10010/console/sshws/Lo6JpqA87KrIt1CO8WF0CjGInZYnZ64RmfkK+u5XTQSjF4s=?cols=136&rows=16' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by shibingli** [comment]
请添加服务器白名单发自我的华为手机-------- 原始邮件 --------主题：[shibingli/webconsole] docker部署控制台报错 登陆进去没有任何反应 (#45)发件人：yangzhenwei-java 收件人：shibingli/webconsole 抄送：Subscribed console.min.js:1 WebSocket connection to 'ws://10.0.8.122:10010/console/sshws/Lo6JpqA87KrIt1CO8WF0CjGInZYnZ64RmfkK+u5XTQSjF4s=?cols=136&rows=16' failed: Error during WebSocket handshake: Unexpected response code: 403

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shibingli/webconsole","title":"shibingli/webconsole","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/shibingli/webconsole"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"docker部署控制台报错  登陆进去没有任何反应 (#45)"}],"action":{"name":"View Issue","url":"https://github.com/shibingli/webconsole/issues/45"}}}
